version: '3.6'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cmkp
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
  cmkp:
    build: .
    environment:
      - MYSQL_HOSTNAME=mysql
    restart: always
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: /cmkp
    ports:
      - 3000:3000
