# fly.toml app configuration file generated for cmkp on 2023-07-27T20:45:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cmkp"
primary_region = "nrt"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
CMKP_EVENT_DAYS = "2"

[build]
dockerfile = "Dockerfile"
